### ISSUE TITLE
Cannot deploy, stuck on "create basic stack"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-dev#71]
For some reason I'm getting: 
![image](https://cloud.githubusercontent.com/assets/128755/4656378/4e8f777c-54d5-11e4-8db9-c414f428babf.png)

Both got stuck on: `TASK: [create basic stack (this will take a while)]`

The configs I tried were `vlad2` and `vlad`:

```

---
region: us-west-2
subdomain: vlad2.dev
hosted_zone: lcip.org
ssl_certificate_name: wildcard.dev.lcip.org
rds_password: Q&}PzHU79J8Ex}3,
cron_time:
  minute: 0
  hour: 0
  month: 1
  day: 1
```

This is a new stack, did I forget some step? I just need a deploy with `
oauth_git_version: register` for testing.
